FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get install -y curl unzip

# Install Node.js
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash && \
   . ~/.nvm/nvm.sh && \
   nvm install 20 && \
   nvm use 20 && \
   nvm alias default 20 && \
   ln -s $(nvm which 20) /usr/local/bin/node

# throw error if node version is <20
RUN . ~/.nvm/nvm.sh && node -v | grep -q "v20" || (echo "Node version is less than 20" && exit 1)

WORKDIR /app

COPY . .

RUN ls -la


# Install bun and add it to the PATH
RUN curl -fsSL https://bun.sh/install | bash && \
   mv /root/.bun/bin/bun /usr/local/bin/bun && \
   bun --version

RUN bun install

CMD ["node", "build/main.js"]