LABEL traefik.http.services.router-proj-tn0-me.loadbalancer.server.port=80
LABEL traefik.http.routers.router-proj-tn0-me.entrypoints=web
LABEL traefik.http.routers.router-proj-tn0-me.rule=Host(`proj.tn0.me`)
LABEL traefik.enable=true
https://github.com/Timmnn/DockerComposeExample